/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface RecoveryApiKeys {
  createdAt: Generated<Timestamp>;
  createdBy: Int8;
  id: string;
  keyHash: string;
  label: string;
  revokedAt: Timestamp | null;
  scope: string;
  tenantId: string;
}

export interface RecoveryAuditEvents {
  actorType: Generated<string>;
  actorUserId: Int8 | null;
  eventHash: string;
  eventType: string;
  id: string;
  objectHash: string;
  objectId: string;
  occurredAt: Generated<Timestamp>;
  previousEventHash: string | null;
  sourceTable: Generated<string>;
  tenantId: string;
}

export interface RecoveryChallengeFindings {
  attributionState: string;
  billedCents: Int8;
  blockerCodes: Generated<Json>;
  category: string;
  confidencePpm: number;
  createdAt: Generated<Timestamp>;
  economicKey: string;
  evidence: Generated<Json>;
  expectedCents: Int8;
  findingHash: string;
  id: string;
  incumbentSnapshotHash: string;
  matchedIncumbentMatterIds: Generated<Json>;
  netNewCandidateCents: Int8;
  populationId: string;
  recordHash: string;
  tenantId: string;
  varianceCents: Int8;
}

export interface RecoveryEligibilityCertifications {
  authorityHash: string;
  buyerAttestationHash: string;
  canonicalFindingId: string;
  certifiedAt: Generated<Timestamp>;
  certifiedBy: Int8;
  currency: string;
  economicKey: string;
  eligibleCents: Int8;
  findingHash: string;
  sourceHash: string;
  tenantId: string;
}

export interface RecoveryFreightRecords {
  billedTotalCents: Int8;
  businessUnit: string;
  buyerId: string;
  createdAt: Generated<Timestamp>;
  currency: string;
  id: string;
  invoiceId: string;
  mode: string;
  payload: Json;
  populationId: string;
  recordHash: string;
  shipmentId: string;
  tenantId: string;
}

export interface RecoveryIncumbentSnapshots {
  frozenAt: Generated<Timestamp>;
  id: string;
  payload: Json;
  populationId: string;
  snapshotHash: string;
  sourceSha256: string;
  tenantId: string;
}

export interface RecoveryIngressReceipts {
  createdAt: Generated<Timestamp>;
  detectedFormat: string;
  filename: string;
  fileSha256: string;
  id: string;
  reasons: Generated<Json>;
  receiptHash: string;
  route: string;
  sizeBytes: Int8;
  status: string;
  tenantId: string;
  transport: string;
}

export interface RecoveryM8VerifiedCashByCurrency {
  currency: string | null;
  tenantId: string | null;
  verifiedMinorUnits: Numeric | null;
}

export interface RecoveryPaymentAuthorizations {
  authorizationHash: string;
  authorizedBy: Int8;
  authorizedCents: Int8;
  createdAt: Generated<Timestamp>;
  id: string;
  instructionId: string;
  reason: string;
  tenantId: string;
}

export interface RecoveryPaymentEvents {
  amountCents: Int8;
  createdAt: Generated<Timestamp>;
  eventHash: string;
  id: string;
  instructionId: string;
  occurredAt: Timestamp;
  provider: string;
  providerReference: string | null;
  sourceHash: string;
  state: string;
  tenantId: string;
}

export interface RecoveryPaymentInstructions {
  amountCents: Int8;
  createdAt: Generated<Timestamp>;
  createdBy: Int8;
  currency: string;
  findingIds: Generated<Json>;
  id: string;
  idempotencyKey: string;
  instructionHash: string;
  payeeId: string;
  payerId: string;
  purpose: string;
  requestSha256: string | null;
  tenantId: string;
}

export interface RecoveryPopulations {
  businessUnit: string;
  buyerId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  populationHash: string;
  status: string;
  tenantId: string;
}

export interface RecoveryReviewDispositions {
  correctedExpectedCents: Int8 | null;
  createdAt: Generated<Timestamp>;
  decision: string;
  dispositionHash: string;
  findingId: string;
  id: string;
  reason: string;
  reviewerUserId: Int8;
  ruleCandidate: string | null;
  tenantId: string;
}

export interface RecoveryTenantMemberships {
  createdAt: Generated<Timestamp>;
  role: string;
  tenantId: string;
  userId: Int8;
}

export interface RecoveryTenants {
  createdAt: Generated<Timestamp>;
  id: string;
  name: string;
  slug: string;
}

export interface RecoveryValueAllocations {
  allocatedAt: Generated<Timestamp>;
  amountCents: Int8;
  currency: string;
  economicKey: string;
  findingId: string;
  id: string;
  instructionId: string;
  tenantId: string;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  loginAttempts: LoginAttempts;
  recoveryApiKeys: RecoveryApiKeys;
  recoveryAuditEvents: RecoveryAuditEvents;
  recoveryChallengeFindings: RecoveryChallengeFindings;
  recoveryEligibilityCertifications: RecoveryEligibilityCertifications;
  recoveryFreightRecords: RecoveryFreightRecords;
  recoveryIncumbentSnapshots: RecoveryIncumbentSnapshots;
  recoveryIngressReceipts: RecoveryIngressReceipts;
  recoveryM8VerifiedCashByCurrency: RecoveryM8VerifiedCashByCurrency;
  recoveryPaymentAuthorizations: RecoveryPaymentAuthorizations;
  recoveryPaymentEvents: RecoveryPaymentEvents;
  recoveryPaymentInstructions: RecoveryPaymentInstructions;
  recoveryPopulations: RecoveryPopulations;
  recoveryReviewDispositions: RecoveryReviewDispositions;
  recoveryTenantMemberships: RecoveryTenantMemberships;
  recoveryTenants: RecoveryTenants;
  recoveryValueAllocations: RecoveryValueAllocations;
  sessions: Sessions;
  userPasswords: UserPasswords;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.
