-- Reference PostgreSQL schema. GitHub Markdown remains the human-auditable projection.
create table if not exists intel_agent (id text primary key, lane text not null, runtime_version text, base_prompt_version text, verified_skill_set_hash text, status text not null default 'ACTIVE');
create table if not exists intel_run (id text primary key, agent_id text references intel_agent(id), parent_run_id text references intel_run(id), started_at timestamptz not null default now(), completed_at timestamptz, hypothesis text, prompt_version text, model_id text, policy_version text, tokens_in bigint default 0, tokens_out bigint default 0, llm_cost numeric default 0, search_cost numeric default 0, compute_cost numeric default 0, outcome text);
create table if not exists intel_candidate (id text primary key, canonical_uri text not null, source_type text not null, exact_revision text, capability_fingerprint text, state text not null, duplicate_of text references intel_candidate(id), sensitivity_state text not null default 'NORMAL', rights_state text);
create table if not exists intel_evidence (id text primary key, candidate_id text not null references intel_candidate(id), canonical_source text not null, exact_revision text not null, retrieved_at timestamptz not null default now(), sha256 text not null, locator text, evidence_type text not null, object_uri text, sensitivity_class text not null default 'NORMAL', redaction_state text not null default 'NONE');
create table if not exists intel_claim (id text primary key, candidate_id text not null references intel_candidate(id), proposition text not null, claim_type text not null, status text not null, confidence_class text, supporting_evidence_ids jsonb not null default '[]', contradicting_evidence_ids jsonb not null default '[]');
create table if not exists intel_verification (id text primary key, candidate_id text not null references intel_candidate(id), frozen_snapshot_hash text not null, verifier_id text not null, verifier_model text, rubric_version text not null, verdict text not null, blocking_findings jsonb not null default '[]', completed_at timestamptz not null default now());
create table if not exists intel_skill (id text not null, version text not null, name text not null, state text not null, interface_schema jsonb not null, implementation_ref text, origin_runs jsonb not null default '[]', origin_tasks jsonb not null default '[]', risk_class text, primary key (id, version));
create table if not exists intel_skill_verification (skill_id text not null, version text not null, heldout_suite_id text not null, pass_count int not null, fail_count int not null, regression_count int not null, adversarial_passed boolean not null default false, adjacent_domain_passed boolean not null default false, evidence_hash text, primary key (skill_id, version, heldout_suite_id));
create table if not exists intel_task_lease (task_id text primary key, owner text not null, generation bigint not null, acquired_at timestamptz not null, expires_at timestamptz not null, payload_hash text);
create table if not exists intel_promotion (candidate_id text primary key references intel_candidate(id), verification_id text references intel_verification(id), score jsonb not null, proposer text not null, approved_by text, decision text not null, master_commit_sha text);
create table if not exists intel_outcome (id text primary key, candidate_id text references intel_candidate(id), experiment_id text, realized_build_days numeric, realized_revenue numeric, realized_savings numeric, failed_reason text, observed_at timestamptz not null default now());
