"""CLI: create a single self-contained synthetic RETALLY operator report.

Data is generated by actual repository Python modules in isolated SQLite files.
This does not use hosted Floot APIs and must not be published as live outcomes.
"""
from __future__ import annotations
import argparse
from html import escape
import json
from pathlib import Path
from datetime import date
import tempfile

from freight.lab_phase4_director import execute_all_labs, priority_actions
from freight.lab_phase4_experiments import conduct_experiments, load_findings
from freight.research_intelligence import phase3_brief, render_html as render_research_html
from freight.test_lab_phase3_real_chain import rating_fixture, funded_store, scenario
from freight.test_lab_assurance import assertions_and_fees, verifier


def snapshot(max_labs: int=14) -> dict:
    with tempfile.TemporaryDirectory(prefix="retally-phase4-research-only-") as temp:
        rec,book=rating_fixture()
        store=funded_store(temp)
        a, fees=assertions_and_fees()
        result=execute_all_labs(record=rec,authority_book=book,store=store,
                                assertions=a,fee_events=fees,verifier=verifier(),
                                contingency=scenario(),max_labs=max_labs)
        campaign=conduct_experiments(register=load_findings(),
            ledger_path=Path(temp)/"phase4_campaign.sqlite3",max_experiments=4,
            record=rec,authority_book=book,store=store,assertions=a,fee_events=fees,
            verifier=verifier(),contingency=scenario())
        result["experiment_campaign"]=campaign
        result["research_intelligence"]=phase3_brief(as_of=date.today())
        result["recommended_next_actions"]=priority_actions(result)
        result["source_context"]={
            "revision_scope":"REPOSITORY_PYTHON_MODULES",
            "hosted_Floot_API_executed":False,
            "production_database_access":False,
            "externally_authenticated_financial_authority":False,
            "simulated_company_customer_count":3,
            "historical_findings_automatically_closed":0,
            "lab_execution_not_production_certification":True
        }
        return result


def render(data: dict) -> str:
    labs=[]
    for item in data["lab_runs"]:
        status=item["status"]
        color="ok" if status.startswith("EXECUTED") else "blocked"
        details=item.get("negative_probe", item.get("reason","not run"))
        lab=escape(str(item["lab"]))
        labs.append(f'<article class="lab {color}"><div class="labnum">{lab}</div><div><h3>{escape(item["title"])}</h3><p class="state">{escape(status)}</p><small>{escape(str(details))}</small></div></article>')
    actions="".join(f'<li>{escape(x["action"])} <span>{escape(x["basis"])}</span></li>' for x in data["recommended_next_actions"])
    experiments="".join(f'<tr><th>{escape(x["finding_id"])}</th><td>{escape(x["cluster"])}</td><td>{escape(x["verdict"])}</td></tr>' for x in data["experiment_campaign"]["recorded_experiments"])
    research=data["research_intelligence"]
    research_rows="".join(
        f'<tr><th>{escape(row["lane"])}</th><td>{row["sourced_observations"]}</td>'
        f'<td>{escape(row["state"])}</td></tr>'
        for row in research["lanes"]
    )
    cohort=data["three_customer_pilot"]
    rows="".join(f'<tr><th>{escape(x["synthetic_customer_id"])}</th><td>{escape(x["state"])}</td><td>{x["simulated_accounting"]["simulated_net_recovered_cents"]/100:,.2f}</td><td>{x["economic_scenario"]["expected_net_margin_cents"]/100:,.2f}</td></tr>' for x in cohort["cohort"])
    return """<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RETALLY | Laboratory Intelligence</title>
<style>
:root{color-scheme:light;--ink:#1c2925;--muted:#607169;--line:#e0e8e2;--green:#117650;--paper:#f7f9f6}
*{box-sizing:border-box}body{background:var(--paper);color:var(--ink);font:15px/1.6 system-ui,-apple-system,sans-serif;margin:0}
main{max-width:1120px;margin:auto;padding:32px 20px 64px}.top{border-bottom:1px solid var(--line);padding-bottom:24px}
.logo{font-size:22px;letter-spacing:.14em;font-weight:800}.logo em{color:var(--green);font-style:normal}
.eyebrow{font-size:11px;letter-spacing:.16em;text-transform:uppercase;color:var(--muted);font-weight:700}
h1{font-size:clamp(31px,4vw,49px);letter-spacing:-.045em;line-height:1.12;margin:18px 0}
h2{font-size:21px;letter-spacing:-.025em}h3{font-size:14px;margin:0}
p,small{color:var(--muted)}small{display:block;font-size:12px}
.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:24px 0}
.stat,.panel,.lab{border:1px solid var(--line);background:white;border-radius:13px;padding:20px}
.stat b{display:block;font:600 32px/1.15 ui-monospace,SFMono-Regular,monospace;margin:10px 0}
.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}
.lab{display:flex;gap:14px;padding:16px;align-items:flex-start}
.labnum{width:30px;height:30px;flex:none;border-radius:8px;background:#eaf5ee;color:var(--green);font-size:13px;font-weight:750;display:grid;place-items:center}
.lab.blocked .labnum{background:#f9e7d6;color:#9c5c18}
.state{font:650 11px/1.4 ui-monospace,monospace;margin:7px 0}
.panel{margin-top:25px}table{border-collapse:collapse;width:100%;font-size:13px}
th,td{text-align:left;border-bottom:1px solid var(--line);padding:13px 7px}
td:nth-child(n+3){font-variant-numeric:tabular-nums;text-align:right}
li{margin:9px 0}li span{display:block;color:var(--muted);font-size:12px}
footer{margin-top:40px;border-top:1px solid var(--line);padding-top:22px;font-size:12px;color:var(--muted)}
@media(max-width:700px){.stats{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}.panel{overflow:auto}}
</style></head><body><main><header class="top"><div class="logo">RETA<em>LL</em>Y</div><div class="eyebrow">Phase 4 / Read-only research results</div>
<h1>What did RETALLY learn?<br>What should change next?</h1><p>Fictional customer fixtures. Executed Python modules are not production deployment or real recovery evidence.</p></header>
<section class="stats"><div class="stat"><div class="eyebrow">Executed modules</div><b>""" +str(len(data["executed_labs"])) +"""/14</b><small>Local synthetic tests</small></div>
<div class="stat"><div class="eyebrow">Blocked / failed</div><b>""" +str(len(data["failed_or_blocked_labs"])) +"""</b><small>Never counted as pass</small></div>
<div class="stat"><div class="eyebrow">Historical open findings</div><b>26</b><small>No automatic closure</small></div>
<div class="stat"><div class="eyebrow">Actual RETALLY revenue</div><b>$0</b><small>Not simulated revenue</small></div></section>
<h2>Laboratory execution receipts</h2><div class="grid">"""+"".join(labs)+"""</div>
<section class="panel"><h2>Three simulated founding customers</h2><p>USD amounts below are entirely fictional; modeled margin can be negative.</p>
<table><thead><tr><th>Customer</th><th>Scenario</th><th>Simulated net recovery</th><th>Modeled margin</th></tr></thead><tbody>"""+rows+"""</tbody></table></section>
<section class="panel"><h2>Actually executed research campaign</h2><p>Four experiments selected from the original 26 findings. INCONCLUSIVE is deliberate: no historical defect is closed merely by running a comparable negative probe.</p><table><thead><tr><th>Original ID</th><th>Root cause</th><th>Closure verdict</th></tr></thead><tbody>"""+experiments+"""</tbody></table></section>
<section class="panel"><h2>Market and oppositional intelligence</h2>
<p>Eight research disciplines, imported vendor claims, internal counterarguments and dated source records. Read-only, not an independent fact check.</p>
<a href="research.html">Open Research Intelligence Workbench ↗</a>
<table><thead><tr><th>Research discipline</th><th>Source-linked items</th><th>Evidence state</th></tr></thead><tbody>"""+research_rows+"""</tbody></table></section>
<section class="panel"><h2>Prioritized next actions</h2><ol>"""+actions+"""</ol></section>
<footer>Data boundary: repository Python under isolated test fixtures; no live Floot API, real bank documents, buyer approval, external carrier operations or deployment. Receipt SHA-256: """+escape(data["receipt_sha256"])+"""</footer></main></body></html>"""


def main():
    parser=argparse.ArgumentParser()
    parser.add_argument("--out",type=Path,required=True)
    parser.add_argument("--max-labs",type=int,default=14)
    args=parser.parse_args()
    data=snapshot(args.max_labs)
    args.out.mkdir(parents=True,exist_ok=True)
    (args.out/"phase4_control.json").write_text(json.dumps(data,sort_keys=True,indent=2)+"\n")
    (args.out/"index.html").write_text(render(data))
    (args.out/"research_intelligence.json").write_text(
        json.dumps(data["research_intelligence"],sort_keys=True,indent=2)+"\n",encoding="utf-8"
    )
    (args.out/"research.html").write_text(
        render_research_html(data["research_intelligence"]),encoding="utf-8"
    )
    print(json.dumps({"executed":data["executed_labs"],
                      "blocked":data["failed_or_blocked_labs"],
                      "receipt":data["receipt_sha256"]},sort_keys=True))


if __name__=="__main__":
    main()
