"""Deterministic, buyer-shareable controlled synthetic Freight pilot bundle.

The archive proves that the current code can replay its synthetic audit,
review, authorized-action, settlement, reversal, and reporting path. It is not
customer evidence, a production-control attestation, or permission to act.
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
from pathlib import Path, PurePosixPath
import tempfile
import zipfile

from freight.synthetic_rehearsal import (
    COUNTER_CSV,
    INVOICE_CSV,
    REVIEW_RULES_CSV,
    SCENARIO_ID,
    SETTLEMENT_CSV,
    VERIFIED_RULES_CSV,
    run_rehearsal,
)


FIXED_ZIP_TIME = (1980, 1, 1, 0, 0, 0)
INPUTS = {
    "inputs/invoices.csv": INVOICE_CSV,
    "inputs/verified-rules.csv": VERIFIED_RULES_CSV,
    "inputs/candidate-rules.csv": REVIEW_RULES_CSV,
    "inputs/settlements.csv": SETTLEMENT_CSV,
    "inputs/returns.csv": COUNTER_CSV,
}


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _json_bytes(value: object) -> bytes:
    return (
        json.dumps(value, sort_keys=True, indent=2, ensure_ascii=False) + "\n"
    ).encode("utf-8")


def _manifest_hash(value: dict) -> str:
    return _sha(
        json.dumps(
            value,
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
        ).encode("utf-8")
    )


def _readme(result: dict) -> bytes:
    metrics = result["metrics"]
    text = f"""# Freight Recovery controlled synthetic pilot

- **Scenario:** `{SCENARIO_ID}`
- **Evidence status:** SYNTHETIC / NO CUSTOMER DATA
- **External action performed:** NO
- **Customer value or revenue claimed:** NO

This archive is a deterministic sales and diligence demonstration generated by
the current Freight Recovery code. It replays three fictional invoices through
scope freeze, rule selection, finding creation, human review, a simulated
buyer-authorized carrier-action receipt, settlement allocation, a later
reversal, and a current report.

## Demonstrated totals

- reviewed discrepancy: ${metrics['reviewed_discrepancy_cents'] / 100:,.2f}
- validated findings: ${metrics['validated_finding_cents'] / 100:,.2f}
- challenger-only validated: ${metrics['challenger_only_validated_cents'] / 100:,.2f}
- net realized after the simulated return: ${metrics['realized_cents'] / 100:,.2f}
- fee-eligible realized: ${metrics['fee_eligible_realized_cents'] / 100:,.2f}

These amounts are invented test data. They do not predict a buyer result,
recovery rate, conversion rate, or price acceptance. The SUBMITTED and delivery
receipts in the trace are simulated proof objects; no email or carrier contact
occurred.

## Contents

- `EXECUTIVE_REPORT.md` — layered buyer report generated from the final state.
- `REVIEW_PACKET.md` — reviewer-facing evidence and decision packet.
- `REHEARSAL_RECEIPT.json` — machine-readable hashes, states, and separate totals.
- `inputs/` — the exact fictional inputs needed to understand the scenario.
- `BUNDLE_MANIFEST.json` — SHA-256 and byte size for every entry.

## Independent verification

From the matching source checkout:

```bash
python -m freight.synthetic_pilot_bundle --verify synthetic-pilot-demo.zip
```

Verification re-runs the controlled scenario and compares every archived byte.
It does not attest production hosting, component rights, external signatures,
or a live customer outcome.
"""
    return text.encode("utf-8")


def build_bundle_entries() -> dict[str, bytes]:
    result = run_rehearsal()
    if result.get("synthetic") is not True:
        raise ValueError("controlled demo must be marked synthetic")
    if result.get("commercial_value_claimed") is not False:
        raise ValueError("controlled demo cannot claim commercial value")
    if result.get("carrier_action_external_action_performed") is not False:
        raise ValueError("controlled demo cannot perform an external action")

    receipt = {
        "schema_version": 1,
        **{
            key: value
            for key, value in result.items()
            if key not in {
                "audit_workflow_summary",
                "report_markdown",
                "review_packet_markdown",
            }
        },
    }
    report_header = (
        "# Controlled synthetic buyer report\n\n"
        "> **SYNTHETIC / NO CUSTOMER DATA.** This is not a customer result, "
        "revenue record, recovery promise, or permission to contact a carrier.\n\n"
    )
    review_header = (
        "# Controlled synthetic reviewer packet\n\n"
        "> **SYNTHETIC / NO CUSTOMER DATA.** All parties, documents, and "
        "amounts are fictional.\n\n"
    )
    entries = {
        "README.md": _readme(result),
        "EXECUTIVE_REPORT.md": (
            report_header + result["report_markdown"] + "\n"
        ).encode("utf-8"),
        "REVIEW_PACKET.md": (
            review_header + result["review_packet_markdown"] + "\n"
        ).encode("utf-8"),
        "REHEARSAL_RECEIPT.json": _json_bytes(receipt),
        "TRACE_SUMMARY.txt": (result["audit_workflow_summary"] + "\n").encode(
            "utf-8"
        ),
        **INPUTS,
    }
    return entries


def _build_manifest(entries: dict[str, bytes]) -> dict:
    body = {
        "schema_version": 1,
        "scenario_id": SCENARIO_ID,
        "synthetic": True,
        "customer_data_included": False,
        "external_action_performed": False,
        "commercial_value_claimed": False,
        "claim_boundary": [
            "All identities, documents, actions, settlements, and amounts are synthetic.",
            "No external message, claim, purchase, or money movement occurred.",
            "The archive proves deterministic internal workflow behavior only.",
            "It does not prove production hosting, rights, security certification, or customer value.",
        ],
        "entries": [
            {"path": path, "size_bytes": len(data), "sha256": _sha(data)}
            for path, data in sorted(entries.items())
        ],
    }
    return body | {"manifest_hash": _manifest_hash(body)}


def _archive_bytes(entries: dict[str, bytes]) -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_STORED) as archive:
        for path, data in sorted(entries.items()):
            info = zipfile.ZipInfo(path, date_time=FIXED_ZIP_TIME)
            info.create_system = 3
            info.compress_type = zipfile.ZIP_STORED
            info.external_attr = 0o100644 << 16
            archive.writestr(info, data)
    return buffer.getvalue()


def build_synthetic_pilot_bundle(destination: str | Path) -> dict:
    destination = Path(destination)
    entries = build_bundle_entries()
    manifest = _build_manifest(entries)
    manifest_bytes = _json_bytes(manifest)
    all_entries = {**entries, "BUNDLE_MANIFEST.json": manifest_bytes}
    archive_bytes = _archive_bytes(all_entries)

    destination.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary_name = tempfile.mkstemp(
        prefix=f".{destination.name}.", suffix=".tmp", dir=destination.parent
    )
    os.close(fd)
    temporary = Path(temporary_name)
    try:
        temporary.write_bytes(archive_bytes)
        os.replace(temporary, destination)
    finally:
        if temporary.exists():
            temporary.unlink()

    return {
        "scenario_id": SCENARIO_ID,
        "bundle_sha256": _sha(destination.read_bytes()),
        "entry_count": len(all_entries),
        "manifest_sha256": _sha(manifest_bytes),
        "manifest_hash": manifest["manifest_hash"],
    }


def verify_synthetic_pilot_bundle(bundle: str | Path) -> dict:
    expected = build_bundle_entries()
    expected_manifest = _build_manifest(expected)
    expected_manifest_bytes = _json_bytes(expected_manifest)
    expected_all = {**expected, "BUNDLE_MANIFEST.json": expected_manifest_bytes}
    with zipfile.ZipFile(bundle, "r") as archive:
        infos = archive.infolist()
        names = [info.filename for info in infos]
        if len(names) != len(set(names)):
            raise ValueError("duplicate synthetic bundle entry")
        for name in names:
            path = PurePosixPath(name)
            if path.is_absolute() or ".." in path.parts or "\\" in name:
                raise ValueError("unsafe synthetic bundle entry path")
        if set(names) != set(expected) | {"BUNDLE_MANIFEST.json"}:
            raise ValueError("synthetic bundle entry set mismatch")

        for info in infos:
            if info.file_size != len(expected_all[info.filename]):
                raise ValueError("synthetic bundle entry size mismatch: " + info.filename)
            if info.compress_type != zipfile.ZIP_STORED:
                raise ValueError("synthetic bundle compression mismatch: " + info.filename)
            if info.date_time != FIXED_ZIP_TIME:
                raise ValueError("synthetic bundle timestamp mismatch: " + info.filename)

        manifest_bytes = archive.read("BUNDLE_MANIFEST.json")
        if manifest_bytes != expected_manifest_bytes:
            raise ValueError("synthetic bundle manifest differs from current code")
        manifest = json.loads(manifest_bytes)
        for key, value in {
            "synthetic": True,
            "customer_data_included": False,
            "external_action_performed": False,
            "commercial_value_claimed": False,
        }.items():
            if manifest.get(key) is not value:
                raise ValueError(f"synthetic bundle {key} boundary mismatch")
        supplied_hash = manifest.get("manifest_hash")
        body = {key: value for key, value in manifest.items() if key != "manifest_hash"}
        if supplied_hash != _manifest_hash(body):
            raise ValueError("synthetic bundle manifest hash mismatch")

        rows = {row.get("path"): row for row in manifest.get("entries", [])}
        if set(rows) != set(expected) or len(rows) != len(manifest.get("entries", [])):
            raise ValueError("synthetic bundle manifest entry set mismatch")
        for path, expected_data in expected.items():
            actual = archive.read(path)
            if actual != expected_data:
                raise ValueError("synthetic bundle entry differs from current code: " + path)
            if rows[path].get("size_bytes") != len(actual):
                raise ValueError("synthetic bundle entry size mismatch: " + path)
            if rows[path].get("sha256") != _sha(actual):
                raise ValueError("synthetic bundle entry hash mismatch: " + path)

    bundle_path = Path(bundle)
    if bundle_path.read_bytes() != _archive_bytes(expected_all):
        raise ValueError("synthetic bundle archive metadata differs from current code")
    return {
        "scenario_id": SCENARIO_ID,
        "bundle_sha256": _sha(bundle_path.read_bytes()),
        "entry_count": len(names),
        "manifest_sha256": _sha(manifest_bytes),
        "manifest_hash": manifest["manifest_hash"],
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("destination", nargs="?")
    parser.add_argument("--verify")
    args = parser.parse_args()
    if args.verify:
        result = verify_synthetic_pilot_bundle(args.verify)
        print("OK controlled synthetic pilot bundle verified " + json.dumps(result, sort_keys=True))
        return
    if not args.destination:
        parser.error("destination path required")
    print(json.dumps(build_synthetic_pilot_bundle(args.destination), sort_keys=True))


if __name__ == "__main__":
    main()
